### ISSUE TITLE
Create a /etc/nubis-$project-release file

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-builder#23]
With version information, similar to /etc/nubis-release.

To ease with diagnosing

**Comment by bhourigan** [comment]
Addressed in 9fb2d4cba8a5cd317210edc834d1d3944219ef1c

**Comment by bhourigan** [comment]
Version is a single string - we don't store the bits separately. If you want just the release or build it should be easy to parse.

**Comment by gozer** [comment]
Something isn't working quite right here. 

root@ip-10-168-1-101:/var/www/mediawiki# cat /etc/nubis-release 
nubis-base 2.119
root@ip-10-168-1-101:/var/www/mediawiki# cat /etc/nubis-nubis-base-release 
nubis-base 2.119

First, looks like nubis-base is getting sort of a duplicate, but I would say that's sort of consistent, even if a tad strange.

2nd, it looks like the file itself is not being generated for non base builds, i.e.

mediawiki images should have a :

/etc/nubis-mediawiki-release

**Comment by bhourigan** [comment]
I think there is some confusion here. I just built nubis-mediawiki 0.66 in airmo and this is what exists:

root@ip-10-165-68-24:/etc# cat nubis-nubis-mediawiki-release
nubis-mediawiki 0.67

The request was for /etc/nubis-$project-release, and in this case the project name is nubis-mediawiki so 'nubis-nubis' is listed. If people are building projects that start with a prefix other than nubis, it will make more sense.

Be sure you're using the latest nubis-builder. You mentioned the other day that you are not using the latest version.

/etc/nubis-release is being created in nubis-base by puppet, so that is independant of what nubis-builder is doing.

**Comment by bhourigan** [comment]
filed https://github.com/Nubisproject/nubis-base/issues/81 for nubis-base and /etc/nubis-release
