### ISSUE TITLE
Version bump sometimes picks an in-use version

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-builder#41]
From http://ci.base.sandbox.nubis.allizom.org/job/base-integration/9/console

1427829478,,ui,error,Build 'amazon-ebs-amazon-linux' errored: Error creating AMI: AMI name nubis-base 2.149 ebs amazon-linux is already in use by AMI ami-995d74a9

**Comment by bhourigan** [comment]
Thanks, I think this is related to some AMIs that existed but were untagged, which is how I look for version conflicts. I deregistered the offending AMIs. I could change the version collision scanner to search by name vs tags, if you think that would be an appropriate alternative.

**Comment by bhourigan** [comment]
Please re-open this issue if you run into this problem again, I am certain it was related to untagged AMIs. My hypothesis is that this happens when you ^C nubis-builder when packer is running, it may not deregister the AMI in all cases. I did test graceful failures (such as a provisioner with a non-zero exit code) and packer does clean it up properly.
